### ISSUE TITLE
Apache Flink

### ISSUE THREAD

**Issue by sirinath** [intel-hadoop/bigDS#1]
Can you add Flink compatibility also.

**Comment by kkasravi** [comment]
Meaning we should allow flink to be a publisher or subscriber? Compatibility can be interpreted in many ways...

**Comment by sirinath** [comment]
Both publisher and subscriber.

**Comment by smarthi** [comment]
I think the BigDS project is targeted within Intel for specific use cases,  there are other groups within Intel that r focused on Graph Analytics and Graph based ML and they are already pursuing Flink. Closing this issue.

**Comment by AllanY** [comment]
Thanks smarthi to help clarify it. Yes we should close the issue.

**Comment by smarthi** [comment]
@AllanY u may want to make this repo private only (Intel only), to not send the wrong signals as to the intent of this project.

**Comment by AllanY** [comment]
Well, BigDS is a public project based on general algorithm and pipeline requirements from real end users. We need to make the included algorithms and pipelines available for those who are really interested in.
